# .streamlit/config.toml

[theme]
# Primary accent for interactive elements
primaryColor = '#7792E3'

# Background color for the main content area
backgroundColor = '#FFFFFF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F8F8FA'

# Color used for almost all text
textColor = '#373737'


#primaryColor="#3fb0e8"
#backgroundColor="#192841"
#secondaryBackgroundColor="#3fb0e8"
#textColor="#f9f9f9"

font = "sans serif"  # Шрифт без засечек

[server]
port = 27369

[browser]
gatherUsageStats = false